In [2]:
#Juego de la vida de conway
import numpy as np
import matplotlib.animation as animation
from matplotlib import cm
import random
#Greenberg Hastings

In [29]:
M=np.arange(1,101).reshape((10,10))
print(M)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [3]:
matriz=np.random.randint(0,2,size=(4,4))
matriz

array([[1, 0, 0, 0],
       [1, 1, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 1]], dtype=int32)

In [44]:
Ma = np.array([[0,1,0],[1,0,1],[0,1,0]])

In [47]:
n=Ma.shape[0]

In [80]:
I = np.identity(n)
L = np.zeros(3)

In [93]:
In = np.insert(I,,L)

In [94]:
In

array([1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.])

In [68]:
np.matmul(I,Ma)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

In [11]:
mat=np.arange(0,100).reshape((10,100))
i=7
j=9

ValueError: cannot reshape array of size 100 into shape (10,100)

In [101]:
def life_game_mod(M):
  n = M.shape[0]
  M_new = np.zeros((n,n))

  for i in range(4):
    for j in range(4):
      state = M[i,j]

      vecinos = M[i:i+2,j-1:j+1]
      numberOfAlive = np.sum(vecinos) - state

      if state == 1:
        if 2 <= numberOfAlive:
          state = 1
        else:
          M_new[i,j] = 0
      else:
        if numberOfAlive == 3:
          state = 1
          M_new[i,j] = state

        return M_new

In [102]:
life_game_mod(matriz)


array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
help(np.pad)

Help on _ArrayFunctionDispatcher in module numpy:

pad(array, pad_width, mode='constant', **kwargs)
    Pad an array.

    Parameters
    ----------
    array : array_like of rank N
        The array to pad.
    pad_width : {sequence, array_like, int}
        Number of values padded to the edges of each axis.
        ``((before_1, after_1), ... (before_N, after_N))`` unique pad widths
        for each axis.
        ``(before, after)`` or ``((before, after),)`` yields same before
        and after pad for each axis.
        ``(pad,)`` or ``int`` is a shortcut for before = after = pad width
        for all axes.
    mode : str or function, optional
        One of the following string values or a user supplied function.

        'constant' (default)
            Pads with a constant value.
        'edge'
            Pads with the edge values of array.
        'linear_ramp'
            Pads with the linear ramp between end_value and the
            array edge value.
        'maximum'
      

In [ ]:
C=np.pad(B,pad_width=1,constant_values=0)
C

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,   0],
       [  0,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,   0],
       [  0,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,   0],
       [  0,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,   0],
       [  0,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,   0],
       [  0,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,   0],
       [  0,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,   0],
       [  0,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,   0],
       [  0,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,   0],
       [  0,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [ ]:
def life_game_mod(C):
  n = M.shape[0]
  M_new = np.zeros((n,n))

   for i in range(n):
   for j in range(n):

      if M[i][j]==1

      vecinos = M[i-1:i+2,j-1:j+1]
      numberOfAlive = np.sum(vecinos) - state

In [ ]:
n=150
m=18

In [ ]:
A=np.random.randint(0,9,size=(10,10))
A

array([[7, 5, 1, 4, 5, 0, 6, 3, 2, 8],
       [1, 1, 5, 6, 6, 3, 0, 8, 5, 4],
       [3, 4, 8, 8, 3, 5, 4, 0, 7, 0],
       [6, 7, 4, 1, 5, 7, 3, 7, 5, 6],
       [4, 6, 5, 6, 7, 2, 7, 8, 6, 1],
       [0, 3, 1, 8, 1, 0, 3, 4, 4, 7],
       [2, 5, 1, 8, 6, 5, 4, 5, 3, 8],
       [0, 2, 0, 8, 1, 6, 1, 5, 6, 0],
       [6, 0, 6, 3, 0, 3, 4, 7, 7, 4],
       [8, 3, 1, 4, 8, 7, 7, 5, 4, 1]])

In [ ]:
def cel_autom(A):
    n = A.shape[0]
    A_new = np.zeros((n,n))

  for i in range(1,n):
    for j in range(1,n):
      state = M[i,j]

      vecinos = M[i-1:i+2,j-1:j+1]
      numberOfAlive = np.sum(vecinos) - state

      if state == 1:
        if 2 <= numberOfAlive <= 3:
          state = 1
        else:
          A_new[i,j] = 0
      else:
        if numberOfAlive == 3:
          A_new[i,j] = 1


In [ ]:
def GH(M,n):
  A_new = np.zeros((n,m))
  for i in range(1,n):
    for j in range(1,m):
      state = M[x][y]

      if state >= 1 and state < n-1: #Exitado a refractario

        state += 1

      elif state == n-1:
        state = 0

      else:





      A_new[x][y] = state
  return A_new




In [ ]:
plt.rcParams["animation.html"] = "jshtml"
plt.rcParams['figure.dpi'] = 130
plt.ioff()


fig, ax = plt.subplots()

def actualizar(i):
  global M
  M = life_game_mod(M)
  plt.cla()
  plt.imshow(M, cmap = "gist_gray")
  plt.title('Game of life')
  plt.xlabel("t = {}",format(i))
  animation.FuncAnimation(fig, actualizar, repeat = false, interval = 1, frames= 201)

NameError: name 'plt' is not defined