In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as ani

In [2]:
#generemos una matriz N x N para iniciar con ceros y unos
N = 4 #es el valor de la dimensión de la matriz
#M = 4
Matriz=np.array([[np.random.randint(0,2) for j in range(N)] for i in range(N)])

In [3]:
print(Matriz) #imprimimos la matriz a "jugar"

[[0 0 1 1]
 [1 0 1 1]
 [1 0 1 0]
 [0 1 1 1]]


In [4]:
#expandimos la matriz a una matriz N+2 x N+2 

####################### explicación de lo que hace np.pad

# Usamos np.pad para agregar ceros alrededor
# El primer argumento es la matriz.
# El segundo argumento es una tupla de tuplas que especifica cuántos ceros agregar
# a cada lado. (arriba, abajo), (izquierda, derecha).
# En este caso, queremos agregar 1 fila y 1 columna de ceros en todos los lados.
# De 3x3 a 5x5, se necesitan 1 fila/columna extra en cada dirección.


#########################

matriz_exp = np.pad(Matriz, ((1, 1), (1, 1)), 'constant', constant_values=0) #Matriz expandidas con primer y ultimo reglón de ceros, y primer y ultima columna en ceros

print(matriz_exp)

[[0 0 0 0 0 0]
 [0 0 0 1 1 0]
 [0 1 0 1 1 0]
 [0 1 0 1 0 0]
 [0 0 1 1 1 0]
 [0 0 0 0 0 0]]


In [5]:
#codigo que estaba pensando en iterar pero no salió

#submatrices
#Sub = M[0:2, 0:2]
#Sub1 = M[0:2, 0:3]
#Sub2 = M[0:2, 1:4]
#sub4 = M[0:2, 2:5]
#segundo renglon
#Sub = M[0:3, 0:2]
#Sub1 = M[0:3, 0:3]
#Sub2 = M[0:3, 1:4]
#sub4 = M[0:3, 2:5]
#tercer renglón
#Sub = M[1:4, 0:2]
#Sub1 = M[1:4, 0:3]
#Sub2 = M[1:4, 1:4]
#sub3 = M[1:4, 2:5]
#Cuarto renglón
Sub = Matriz[2:4,0:2]
Sub1 = Matriz[2:4, 0:3]
Sub2 = Matriz[2:4, 1:4]
sub3 = Matriz[2:4, 2:5]

Sub
m

NameError: name 'm' is not defined

In [6]:
#matriz_exp,1]

In [7]:
#Tu funcion juego de la vida


#def life_game_mod(M):
n = matriz_exp.shape[0] #es la dimensión de tu matriz expandida
M_new = np.zeros((n,n)) #matriz de ceros de igual tamaño que la matriz expandida

print(matriz_exp) #imprime la matriz antes de jugar
for k in range(3): #cuantas veces quieres jugar
    for i in range(1,N+1):
        for j in range(1,N+1):
            state =matriz_exp[i][j] #Elemento ij
            vecinos = matriz_exp[i-1:i+2,j-1:j+2] #vecinos del elemento ij
            numberOfAlive = np.sum(vecinos) - state #numero de vida
            #print(vecinos)
            #print(numberOfAlive)
    
            if numberOfAlive < 3:
                M_new[i][j] = 0
            else:
                M_new[i][j] = 1
    matriz_exp = M_new #para que funcione volver a jugar más de una vez, la matriz expandida es igual a la nueva matriz
    print(matriz_exp)
   # if 2 <= numberOfAlive:
   #      state = 1
   #    else:
   #      M_new[i,j] = 0
   #  else:
   #    if numberOfAlive == 3:
   #      state = 1
   #      M_new[i,j] = state
#
        #return M_new
        

[[0 0 0 0 0 0]
 [0 0 0 1 1 0]
 [0 1 0 1 1 0]
 [0 1 0 1 0 0]
 [0 0 1 1 1 0]
 [0 0 0 0 0 0]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
#conjetura si sum(matriz) > N**2/2  vive